### ISSUE TITLE
Auto-upload shots to visualizer

### ISSUE THREAD

**Issue by ebengoechea** [ebengoechea/dye_de1app_dsx_plugin#13]
Several users have requested auto-upload to Visualizer as soon as the shot is done.

This is already available on @mimoja 's Visualizer extension, and I want to directly invoke her extension instead of having the upload functions inside DYE, but this will be done only when the extension goes out of beta and into the stable branch.

Also, for me to do auto-upload it is imperative that DYE allows to re-upload the shot to Visualizer when you change its metadata. Given the current UI, I don't see a clear way of including it in an already crowded page, so I'm waiting till I implement some way of triggering additional actions on shots (see [issue #12](https://github.com/ebengoechea/dye_de1app_dsx_plugin/issues/12)).

**Comment by miharekar** [comment]
I assume most people use Visualizer on their phones/computers, and not Decent tablet.

So for me it would be useful if the "Upload to Visualizer" button would always stay like that and not change to "See in Visualizer".

Maybe it could be a settings toggle to support both, but in my opinion, most users would want to reupload, rather than open in tablet Chrome. Which is not great, to say the least 😅

**Comment by ebengoechea** [comment]
Ok, I'll look into it, and move the "See in Visualizer" option to the future menu for additional actions.

**Comment by ebengoechea** [comment]
Enhancement implemented on version 1.17.
